import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowLeft, BadgeCheck, BrainCircuit, Crown, EyeOff, Heart, History, Rocket } from "lucide-react";
import { Button } from "@/components/ui/button";

export const Route = createFileRoute("/premium")({ head: () => ({ meta: [{ title: "SwipeIt+ — Découverte illimitée" }, { name: "description", content: "Découvrez SwipeIt+ à 4,99 € par mois." }] }), component: PremiumPage });
const features = [[EyeOff,"Aucune publicité"],[Heart,"Favoris illimités"],[History,"Historique complet"],[BrainCircuit,"IA de recommandation avancée"],[BadgeCheck,"Badges exclusifs"],[Rocket,"Accès anticipé"]] as const;
function PremiumPage() {
  return <main className="ambient-grid relative min-h-screen overflow-hidden bg-background px-5 pb-10 text-foreground"><div className="pointer-events-none absolute inset-x-0 top-0 h-[520px] bg-[radial-gradient(circle_at_50%_0%,var(--primary),transparent_58%)] opacity-25" /><div className="relative mx-auto max-w-lg pt-6"><Button asChild variant="glass" size="icon" className="rounded-full"><Link to="/profile"><ArrowLeft /></Link></Button><section className="mt-10 text-center"><span className="mx-auto grid h-20 w-20 place-items-center rounded-[1.5rem] bg-primary text-primary-foreground shadow-[var(--shadow-blue)]"><Crown className="h-9 w-9" /></span><p className="mt-7 text-[10px] font-bold uppercase tracking-[.27em] text-primary">La découverte réinventée</p><h1 className="mt-4 font-display text-4xl font-semibold uppercase tracking-[-.07em]">SwipeIt<span className="text-primary">+</span></h1><p className="mx-auto mt-4 max-w-sm text-sm leading-relaxed text-muted-foreground">Plus de limites. Plus de contrôle. Des recommandations qui deviennent vraiment les vôtres.</p></section>
      <section className="mt-9 rounded-[2rem] bg-card/80 p-6 ring-1 ring-border backdrop-blur-xl"><div className="grid grid-cols-2 gap-3">{features.map(([Icon,label]) => <div key={label} className="flex items-start gap-3 rounded-2xl bg-secondary p-3"><Icon className="mt-0.5 h-4.5 w-4.5 shrink-0 text-primary" /><span className="text-xs font-semibold leading-relaxed">{label}</span></div>)}</div><div className="mt-7 text-center"><p><span className="font-display text-4xl font-semibold">4,99 €</span><span className="text-sm text-muted-foreground"> / mois</span></p><p className="mt-1 text-xs text-muted-foreground">Annulable à tout moment</p></div><Button variant="premium" size="xl" className="mt-6 w-full" onClick={() => window.alert("Merci ! L’abonnement de démonstration est prêt.")}>Essayer SwipeIt+ gratuitement</Button><p className="mt-3 text-center text-[10px] text-muted-foreground">7 jours gratuits, puis 4,99 €/mois.</p></section></div></main>;
}